spring:
  application:
    name: Service-Goods
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/day1209_alicloud_shop?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  # Spring-Cloud-Ali注册中心组件Nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # 配置Sentinel控制台(一个Spring Boot服务)通信端口和服务注册地址
    sentinel:
      transport:
        # 与控制台服务通信的端口(任意配置)
        port: 9999
        # 控制台服务地址
        dashboard: localhost:8080
server:
  port: 8859